gzip = true
stats = true
index-stats = true
index-as-update=true

elasticsearch-max-conns = 10
elasticsearch-max-seconds = 5
elasticsearch-max-bytes = 8000000

dropped-collections = true
dropped-databases = true

resume = true
resume-write-unsafe = true
resume-name = "default"
verbose = true

direct-read-namespaces = ["{DB.COLLECTION_VIEW}"]

[[relate]]
namespace = "{DB.COLLECTION}"
with-namespace = "{DB.COLLECTION_VIEW}"

[[mapping]]
namespace = "{DB.COLLECTION_VIEW}"
index = "{INDEX}"
